# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gApi', '0002_news_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobbole_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.CharField(max_length=200, verbose_name='自我描述')),
                ('detail_info_url', models.CharField(max_length=300, verbose_name='详情链接')),
                ('detail_info_url_object_id', models.CharField(max_length=50, verbose_name='链接的加密')),
                ('publish_time', models.CharField(max_length=45, verbose_name='发布时间')),
                ('location', models.CharField(max_length=45, verbose_name='地址')),
                ('fav_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '相亲信息',
                'verbose_name_plural': '相亲信息',
            },
        ),
    ]
