# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gApi', '0003_jobbole_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbole_date',
            name='detail_info_url',
            field=models.URLField(max_length=300, verbose_name='详情链接'),
        ),
        migrations.AlterField(
            model_name='jobbole_date',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='喜欢数'),
        ),
        migrations.AlterField(
            model_name='jobbole_date',
            name='location',
            field=models.CharField(max_length=45, verbose_name='发布地址'),
        ),
    ]
