# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gApi', '0005_jobbole_detail_data_jobbole_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbole_detail_data',
            name='images_url_datas',
        ),
    ]
